# These are supported funding model platforms

github: #
patreon: #
open_collective: #
ko_fi: apokalypt
tidelift: #
community_bridge: #
liberapay: #
issuehunt: #
otechie: #
lfx_crowdfunding: #
custom: #
