name: Feature request
description: Suggest an idea for this extension
title: "[FEATURE] "
labels: ['enhancement']

body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to be implemented to fix your problem.
    validations:
      required: true
  - type: textarea
    id: additional_notes
    attributes:
      label: Additional notes
      description: Add any other notes about the suggestion here.
