name: Question
description: Ask a specific question about this extension
title: "[ASK] "
labels: ['question']

body:
  - type: textarea
    id: description
    attributes:
      label: What's your question?
      description: A clear and concise question about the project
    validations:
      required: true
  - type: textarea
    id: additional_notes
    attributes:
      label: Additional notes
      description: Add any other notes about the question here.
